language: go

go:
  - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y proftpd-basic

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
