os:
  - osx
  - linux

language: go

go:
  - master

before_install:
  - env
  - sudo apt-get -qq update
  - sudo apt-get install -y proftpd-basic
  - sudo useradd -p $(openssl passwd -1 test) -m -s /bin/bash test
  - curl -T gotest.go -u test:test ftp://localhost/test.go

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
